### Streamlining Your Research Laboratory with Python
* Authors:   Mark F. Russo, Ph.D and William Neil 
* Publisher: John Wiley & Sons, Inc.
* License:   MIT (https://opensource.org/licenses/MIT)

In [1]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 13]])
arr.dtype

dtype('int64')

In [2]:
arr[0,:]

array([1, 2, 3, 4])

In [3]:
arr[:,2]

array([ 3,  7, 11])

In [4]:
arr[1:,2:]

array([[ 7,  8],
       [11, 13]])

In [5]:
sub = arr[1:,2:] 
sub

array([[ 7,  8],
       [11, 13]])

In [6]:
sub[1,1]

np.int64(13)

In [7]:
sub[1,1] = 13
sub

array([[ 7,  8],
       [11, 13]])

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13]])

In [9]:
arr * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 26]])

In [10]:
arr / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6.5]])

In [11]:
arr // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [12]:
arr % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 1]])